spring:
  profiles:
    default: demo
  datasource:
    url: jdbc:h2:mem:polizas;DB_CLOSE_DELAY=-1
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: false
server:
  port: 8080
app:
  api-key: ${APP_API_KEY:123456}
core:
  base-url: ${CORE_BASE_URL:http://localhost:8080}
